name: Node.js Package

on:
  release:
    types: [created]
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.14.1
      - run: yarn
      - run: yarn test

#################### Não publicar ainda
  # publish-npm:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12.14.1
  #         registry-url: https://registry.npmjs.org/
  #     - run: yarn
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
